<?php

namespace Sdl\LiteralType;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-01 at 00:30:25.
 */
class LiteralTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var LiteralType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SdlString("Hello World!");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Sdl\LiteralType\LiteralType::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->assertEquals($this->object->getType(),"SdlString");
    }

    /**
     * @covers Sdl\LiteralType\LiteralType::castTo
     * @todo   Implement testCastTo().
     */
    public function testCastTo()
    {
        // Remove the following lines when you implement this test.
        $int_value = $this->object->castTo(new SdlInteger);
        $this->assertEquals($int_value->getType(),"SdlInteger");
        $this->assertEquals($int_value->getValue(),0);
        $int_value->setValue(1);
        $this->assertEquals($int_value->getValue(),1);

        $bool_value = $int_value->castTo(new SdlBoolean);
        $this->assertEquals($bool_value->getType(),"SdlBoolean");
        $this->assertEquals($bool_value->getValue(),true);
        
        $bool_value2 = $this->object->castTo(new SdlBoolean);
        $this->assertEquals($bool_value2->getValue(),true);
        
    }

}
