<?php

namespace Sdl\LiteralType;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-04 at 02:32:57.
 */
class SdlIntegerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SdlInteger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SdlInteger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Sdl\LiteralType\SdlInteger::setValue
     * @covers Sdl\LiteralType\SdlInteger::getValue
     */
    public function testSetValue()
    {
        $this->object->setValue("123");
        $this->assertEquals(123,$this->object->getValue());
        $this->object->setValue(234);
        $this->assertEquals(234,$this->object->getValue());
        $this->object->setValue(345.6);
        $this->assertEquals(345,$this->object->getValue());
    }

    /**
     * @covers Sdl\LiteralType\SdlInteger::setSdlLiteral
     * @covers Sdl\LiteralType\SdlInteger::getSdlLiteral
     * @todo   Implement testSetSdlLiteral().
     */
    public function testSetSdlLiteral()
    {
        $this->object->setSdlLiteral("123");
        $this->assertEquals("123",$this->object->getSdlLiteral());
        $this->object->setSdlLiteral(234);
        $this->assertEquals("234",$this->object->getSdlLiteral());
        $this->object->setSdlLiteral(345.6);
        $this->assertEquals("345",$this->object->getSdlLiteral());
    }


}
