<?php

namespace Sdl\LiteralType;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-04 at 02:30:45.
 */
class SdlNullTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SdlNull
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SdlNull;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Sdl\LiteralType\SdlNull::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue()
    {
        $this->object->setValue(123);
        $this->assertEquals(null,$this->object->getValue());
    }

    /**
     * @covers Sdl\LiteralType\SdlNull::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue()
    {
        $this->assertEquals(null,$this->object->getValue());
        $this->object->setValue(123);
        $this->assertEquals(null,$this->object->getValue());
    }

    /**
     * @covers Sdl\LiteralType\SdlNull::setSdlLiteral
     * @todo   Implement testSetSdlLiteral().
     */
    public function testSetSdlLiteral()
    {
        $this->assertEquals("null",$this->object->getSdlLiteral());
        $this->object->setSdlLiteral("null");
        $this->assertEquals("null",$this->object->getSdlLiteral());
    }

    /**
     * @covers Sdl\LiteralType\SdlNull::getSdlLiteral
     * @todo   Implement testGetSdlLiteral().
     */
    public function testGetSdlLiteral()
    {
        $this->assertEquals("null",$this->object->getSdlLiteral());
    }

}
