<?php

namespace Sdl;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-03 at 03:10:21.
 */
class SdlCommentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SdlComment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SdlComment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Sdl\SdlComment::getTagName
     * @todo   Implement testGetTagName().
     */
    public function testGetTagName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlComment::setCommentStyle
     * @todo   Implement testSetCommentStyle().
     */
    public function testSetCommentStyle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlComment::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlComment::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlComment::encodeTag
     * @todo   Implement testEncodeTag().
     */
    public function testEncodeTag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
