<?php

namespace Sdl;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-03 at 03:10:21.
 */
class SdlCommentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SdlComment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SdlComment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Sdl\SdlComment::getTagName
     * @todo   Implement testGetTagName().
     */
    public function testGetTagName()
    {
        $this->assertEquals($this->object->getTagName(), "@COMMENT");
    }

    /**
     * @covers Sdl\SdlComment::setCommentStyle
     * @covers Sdl\SdlComment::setValue
     * @covers Sdl\SdlComment::getValue
     * @covers Sdl\SdlComment::encodeTag
     * @todo   Implement testSetCommentStyle().
     */
    public function testSetCommentStyle()
    {

        foreach( array(SdlComment::STYLE_PHP, SdlComment::STYLE_HASH, SdlComment::STYLE_DASH) as $style) {
            SdlComment::setCommentStyle($style);
            $comment = new SdlComment();
            $comment->setValue("Hello World");
            $sdl = $comment->encodeTag();
            $expect = $style." Hello World";
            $this->assertEquals($expect, $sdl);
        }

    }
}
