<?php

namespace Sdl;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-02 at 02:04:09.
 */
class SdlTagTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var SdlTagNew
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SdlTag;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Sdl\SdlTagNew::setTagName
     * @todo   Implement testSetTagName().
     */
    public function testSetTagName()
    {
        // Remove the following lines when you implement this test.
        $this->object->setTagName("foo:bar");
        $this->assertEquals($this->object->getTagName(),"foo:bar");
    }

    /**
     * @covers Sdl\SdlTagNew::hasAttribute
     * @todo   Implement testHasAttribute().
     */
    public function testHasAttribute()
    {
        $this->assertFalse($this->object->hasAttribute("foo"));
        $this->object->setAttribute("foo","bar");
        $this->assertTrue($this->object->hasAttribute("foo"));
    }

    /**
     * @covers Sdl\SdlTagNew::getAttribute
     * @todo   Implement testGetAttribute().
     */
    public function testGetAttribute()
    {
        $this->object->setAttribute("foo","bar");
        $this->assertEquals($this->object->getAttribute("foo"),"bar");
    }

    /**
     * @covers Sdl\SdlTagNew::setAttribute
     * @todo   Implement testSetAttribute().
     */
    public function testSetAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlTagNew::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlTagNew::setValuesFromArray
     * @todo   Implement testSetValuesFromArray().
     */
    public function testSetValuesFromArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlTagNew::hasChildren
     * @todo   Implement testHasChildren().
     */
    public function testHasChildren()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlTagNew::getChildren
     * @todo   Implement testGetChildren().
     */
    public function testGetChildren()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlTagNew::addChild
     * @todo   Implement testAddChild().
     */
    public function testAddChild()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlTagNew::createChild
     * @todo   Implement testCreateChild().
     */
    public function testCreateChild()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlTagNew::end
     * @todo   Implement testEnd().
     */
    public function testEnd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlTagNew::getParent
     * @todo   Implement testGetParent().
     */
    public function testGetParent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Sdl\SdlTagNew::setParent
     * @todo   Implement testSetParent().
     */
    public function testSetParent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testCreateComment()
    {
        $out = $this->object->createComment("Hello World")->encode();
        $this->assertEquals("# Hello World\n", $out);
    }
    
    /**
     * @covers Sdl\SdlTagNew::encode
     * @todo   Implement testEncode().
     */
    public function testEncode()
    {
        $out = $this->object
            ->createChild("foo")
                ->createChild("bar")
                    ->setValuesFromArray([1,2,3])
                    ->end()
                ->createChild("baz")
                    ->setValuesFromArray(["do","re","mi"])
                    ->end()
                ->end()
            ->encode();
        $expect = "foo {\n    bar 1 2 3\n    baz \"do\" \"re\" \"mi\"\n}\n";
        $this->assertEquals($expect,$out);
    }

}
